name: name_casertano

services:
  api:
    build: .
    container_name: name_casertano
    restart: unless-stopped
    command:
      - node
      - api/src/index.js
      - api

    env_file:
      - www/.env

    volumes:
      - ./@storage/images/projects:/app/@storage/images/projects

    ports:
      - "3001:3001"

    deploy:
      resources:
        limits:
          memory: 128M

    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"
