name: name_casertano

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile

    env_file:
      - .env

    ports:
      - "3008:3001"

    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 128M

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_TURNSTILE_SITE_KEY
        - NEXT_PUBLIC_CONTACT_EMAIL
        - NEXT_PUBLIC_NAME
        - NEXT_PUBLIC_VAT
        - NEXT_PUBLIC_SOCIAL_LINKEDIN
        - NEXT_PUBLIC_SOCIAL_GITHUB
        - NEXT_PUBLIC_SOCIAL_TELEGRAM

    depends_on:
      - api

    environment:
      - NODE_ENV=production

    ports:
      - "8081:80"

    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 256M
