/*
 * Dario Casertano <dario@casertano.name>
 * Copyright (c) 2026 Casertano Dario – All rights reserved.
 * Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International.
 */

export const projects: Projects.Project[] = [
    {
        slug: "falco-ws-environment",
        title: "Piattaforma integrata per l'industria manifatturiera — gestionale, IoT e acquisti",
        short: "Piattaforma integrata per la manifattura: gestionale PWA con Gantt, monitoraggio IoT via MQTT e acquisti ERP Dolibarr.",
        tags: ["Node.js", "Vue 3", "MQTT", "Docker", "Dolibarr"],
        description: "Piattaforma end-to-end per l'industria manifatturiera che copre l'intero ciclo produttivo — gestionale, monitoraggio IoT e acquisti — con un backend REST da 196 endpoint su 18 domini, una PWA Vue 3 con Gantt Syncfusion per la pianificazione a ore e una dashboard telemetria real-time via MQTT. L'ERP Dolibarr containerizzato gestisce il flusso acquisti, mentre l'infrastruttura Docker su Ubuntu con Apache e monitoring Sentry garantisce affidabilità su scala industriale.",
        features: [
            "Backend REST con 196 endpoint su 18 domini (ordini, preventivi, progetti, commesse, macchine), validati con Joi e documentati da una Postman collection autogenerata dagli schemi",
            "Monitoraggio IoT real-time: broker MQTT Mosquitto con 8 worker per macchina che ingeriscono telemetria, calcolano report e inviano alert push via Firebase Cloud Messaging",
            "PWA gestionale Vue 3 con Gantt Syncfusion EJ2 per pianificare task a ore con dipendenze e lag in minuti, state Pinia e storage offline IndexedDB",
            "Dashboard IoT PWA con telemetria real-time, tachimetri, Chart.js e statistiche per reparto",
            "Processi automatizzati: sincronizzazione CNC via FTP, report periodici e notifiche push; documenti DOCX, PDF ed export XLSX generati programmaticamente",
            "Infrastruttura Docker Compose (MariaDB, Mosquitto, worker LibreOffice) su Ubuntu con Apache e Let's Encrypt, monitoring Sentry/GlitchTip ed ERP Dolibarr per gli acquisti",
        ],
        skills: [
            "Node.js 22", "TypeScript", "Express", "TypeORM", "Joi",
            "Vue", "Vuetify 4", "PWA", "IndexedDB",
            "MariaDB", "MQTT", "Mosquitto", "Firebase Cloud Messaging",
            "Docker", "Dolibarr",
        ],
        media: [],
    },
    {
        slug: "mail-thinker-ai",
        title: "Agente AI autonomo per la gestione intelligente della posta",
        short: "Agente AI autonomo che legge, analizza e gestisce la posta in linguaggio naturale su Gmail e mailbox IMAP.",
        tags: ["LangChain", "OpenAI", "Vue 3", "Docker", "Gmail API"],
        description: "Agente AI autonomo che legge, analizza e gestisce la posta elettronica in linguaggio naturale, combinando i modelli OpenAI con un design transport-agnostic: Gmail API via OAuth2 e qualsiasi mailbox IMAP. Il backend Node.js/TypeScript usa DeepAgents e LangChain per il tool-calling su Express.js, TypeORM e MariaDB; il frontend è una SPA Vue 3/Vuetify che riproduce in streaming le risposte dell'agente via SSE. Credenziali protette con cifratura AES-256-GCM e key encapsulation RSA, stack orchestrato con Docker per sviluppo e produzione.",
        features: [
            "Agente AI autonomo con DeepAgents e LangChain: tramite tool-calling cerca, legge e analizza conversazioni email in linguaggio naturale",
            "Doppio transport email — Gmail API via OAuth2 e IMAP (imapflow) — con credenziali cifrate AES-256-GCM e key encapsulation RSA",
            "Parser allegati interamente JavaScript per PDF, DOCX, XLSX, PPTX e immagini, analizzate con OpenAI Vision API",
            "Rilevamento automatico delle cartelle della mailbox e ricostruzione dei thread via header In-Reply-To e References",
            "HTTP API Express con risposte firmate JWT, validazione Zod e middleware di autenticazione centralizzati",
            "SPA Vue 3 e Vuetify con login, gestione mailbox e chat in streaming SSE, i18n IT/EN e installabile come PWA",
        ],
        skills: [
            "TypeScript", "Node.js", "Express.js", "TypeORM", "MariaDB",
            "DeepAgents", "LangChain", "OpenAI", "OpenAI Vision",
            "Gmail API", "IMAP", "OAuth2", "Vue 3", "Vuetify", "Docker",
        ],
        media: [],
    },
    {
        slug: "disaster-relief-department",
        title: "Monitoraggio e distribuzione near-realtime di allerte meteo e sismiche",
        short: "Piattaforma TypeScript/Node.js che raccoglie, processa e distribuisce in near-realtime allerte meteo-idrogeologiche e sismiche su tutto il territorio italiano.",
        tags: ["Telegram Bot", "GIS", "OpenAI", "Docker", "WebSocket"],
        description: "Piattaforma backend TypeScript/Node.js che automatizza l'intero flusso di monitoraggio e distribuzione near-realtime delle allerte della Protezione Civile e dei dati sismici di INGV, USGS ed EMSC/CSEM su tutto il territorio italiano. Converte i dati grezzi in GeoJSON/KML, li persiste su SQLite e notifica in tempo reale via Telegram Bot e Firebase Storage, orchestrando tutto su tre servizi Docker con tracciamento errori via Sentry.",
        features: [
            "Ingestion real-time via WebSocket di EMSC SeismicPortal: deduplicazione, filtro geografico sul bounding box italiano e riconnessione con backoff esponenziale",
            "Cronjob idempotenti (DPC ogni 2 min, INGV/USGS ogni 5 min) con lock file-based e tracciamento SHA per un'acquisizione affidabile",
            "Pipeline geospaziale TopoJSON → GeoJSON → KML con riproiezione EPSG:4326 e classificazione automatica in livelli GIALLA, ARANCIONE e ROSSA",
            "Classificazione delle zone di allerta assistita da OpenAI come fallback, con cache su file per le regioni già risolte",
            "Telegram Bot (grammY) con registrazione approvata da admin, controllo accessi e notifiche push in base alla severità",
            "Infrastruttura Docker Compose su tre servizi (cronjob, telegram-bot, seismic) con build tipizzato e deploy remoto via rsync",
        ],
        skills: [
            "TypeScript", "Node.js 22", "yargs", "grammY", "Telegram API",
            "OpenAI API", "Firebase", "WebSocket", "EMSC/CSEM", "DPC", "INGV", "USGS",
            "SQLite", "TypeORM", "Migrazioni", "GeoJSON", "KML", "ogr2ogr", "TopoJSON",
            "Docker", "Docker Compose", "rsync", "Sentry",
        ],
        media: [],
    },
    {
        slug: "piattaforma-gestione-territoriale",
        title: "Piattaforma di gestione territoriale",
        short: "Sistema per organizzazioni con sedi, turni e risorse: due PWA, bot Telegram, reportistica e manutenzione su backend MariaDB containerizzato.",
        tags: ["Vue", "Node.js", "Docker", "Strapi 5"],
        description: "Sistema end-to-end per organizzazioni con sedi operative, turnistica, risorse umane, manutenzione e reportistica su scala territoriale. Due PWA (admin backoffice + client operativo) e bot Telegram coprono l'intero flusso: gestione turni e sostituzioni, notifiche push, code messaggi dual-channel e generazione documenti. Infrastruttura containerizzata con backend REST su MariaDB e CMS Strapi 5 per guide multilingua.",
        features: [
            "Due PWA (admin + operativo) con routing lazy-loaded, Vuex e service worker per installazione e utilizzo offline",
            "Backend REST con 19 entità su MariaDB, autenticazione JWT per ruolo e validazione Joi",
            "Bot Telegram per gestione turni, candidature e notifiche push con conversazioni interattive",
            "Sistema code messaggi dual-channel (in-app + email) con priorità, template DOCX e tracciamento consegna",
            "9 cronjob per attivazione turni, reminder report, notifiche manutenzione e sync CMS",
            "Infrastruttura containerizzata Docker Compose (5 servizi) con Apache reverse proxy",
        ],
        skills: [
            "Node.js", "Express", "TypeORM", "MariaDB", "JWT", "Joi",
            "Vue", "Vuetify", "PWA", "TypeScript", "Vuex", "Service Worker",
            "grammy", "Docker", "Docker Compose", "Apache",
            "Strapi 5", "Sentry", "Docxtemplater",
        ],
        media: [],
    },
    {
        slug: "motore-di-ricerca-multi-contesto",
        title: "Motore di ricerca multi-contesto con sincronizzazione P2P",
        short: "PWA offline-first che unifica motori di ricerca con CSE dedicati e sincronizza dispositivi in tempo reale via WebRTC P2P.",
        tags: ["Vue", "WebRTC", "PWA", "Docker", "Firebase"],
        description: "PWA che unifica più domini di ricerca in un'unica interfaccia, ciascuno servito da un Google Custom Search Engine profilato per lingua (EN, IT, FR). La sincronizzazione P2P end-to-end cifrata via WebRTC — con discovery su Firebase Realtime Database e server TURN autogestito — consente la condivisione di cronologia e segnalibri tra dispositivi senza backend tradizionale. L'architettura offline-first con Dexie/IndexedDB e Workbox garantisce funzionalità completa anche in assenza di connessione.",
        features: [
            "Ricerca multi-contesto con CSE dedicati per lingua (EN, IT, FR), tab switching immediato e persistenza dello stato in sessione",
            "Sincronizzazione P2P end-to-end cifrata via WebRTC con discovery su Firebase, trasferimento a chunk su DataChannel e server TURN autogestito per NAT traversal",
            "Server TURN coturn containerizzato con autenticazione HMAC-SHA1, Apache reverse proxy, Let's Encrypt e rate limiting",
            "Persistenza offline con Dexie (IndexedDB): cronologia, segnalibri, backup cifrato e merge bidirezionale tra dispositivi",
            "PWA installabile con Workbox Service Worker, caching strategico, wake lock e supporto Android/iOS",
            "Deploy automation con Vite + Firebase Hosting + Docker Compose, monitoring Sentry e SRI a build",
        ],
        skills: [
            "Vue", "TypeScript", "Vuetify 3", "Composition API", "Vite", "Pinia",
            "WebRTC", "TURN/STUN", "coturn", "Node.js", "Firebase Realtime DB",
            "Docker", "Docker Compose", "Workbox", "Dexie.js", "Sentry",
        ],
        media: [],
    },
    {
        slug: "bitmonds",
        title: "NFT Marketplace per diamanti virtuali collezionabili tokenizzati su Polygon",
        short: "Diamanti virtuali tokenizzati in NFT ERC-721 su Polygon: marketplace on-chain, back-office PWA e rendering 3D automatico.",
        tags: ["Solidity", "Polygon", "ERC-721", "Vue", "Node.js"],
        description: "Piattaforma end-to-end per la tokenizzazione di diamanti virtuali in NFT ERC-721 su Polygon. Combina smart contract Solidity con marketplace on-chain, back-office PWA in Vue 2 per gestione token e artworks, e un ecosistema di backend distribuiti (PHP Zend Framework 3 per sito pubblico con Nexi/PayPal, Node.js/Express per daemon blockchain, rendering texture 3D e code di processing). L'infrastruttura PM2 in cluster mode orchestra tutti i servizi su MariaDB multi-database con storage IPFS per metadati e asset digitali.",
        features: [
            "Smart contract ERC-721 con marketplace on-chain, royalties EIP-2981 e minting/drop/burn su Polygon per tokenizzare diamanti virtuali in NFT",
            "Back-office PWA con MetaMask e Firebase: gestione catalogo token, artworks e operazioni on-chain tramite smart contract",
            "Sito e-commerce PHP Zend Framework 3: catalogo diamanti, pagamenti Nexi/PayPal, KYC e voucher",
            "Daemon blockchain Node.js per mirroring e caching dello stato on-chain con drops schedulati e queue processing",
            "Logistics V3: suite backend Node.js con Renderer Bot per texture 3D, Viewer NFT interattivo e API client/admin",
            "Infrastruttura PM2 cluster mode su MariaDB multi-database con storage IPFS/Filebase per metadati e asset",
        ],
        skills: [
            "Solidity", "Ethers.js", "Polygon", "ERC-721",
            "PHP", "Zend Framework 3", "Node.js", "Express",
            "TypeORM", "MariaDB", "Vue", "Vuetify",
            "PWA", "Firebase", "MetaMask", "IPFS",
            "PM2", "Filebase",
        ],
        media: [],
    },
]
